name: Docker

on:
  push:
    branches: [ depoly ]

jobs:
  build:
    runs-on: ubuntu-24.04

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 4852
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=5s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: List build artifacts
        run: ls -R build/libs

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy JAR file to EC2
        run: |
          scp -o StrictHostKeyChecking=no build/libs/ProjectA-0.0.1-SNAPSHOT.jar ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/ProjectA-0.0.1-SNAPSHOT.jar

      - name: Stop running application on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} "pkill -f 'ProjectA-0.0.1-SNAPSHOT.jar' || true"

      - name: cp jarFile to container
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} "java -jar -Dspring.profiles.active=prod /home/ubuntu/ProjectA-0.0.1-SNAPSHOT.jar &"